<?php

use Faker\Generator as Faker;
use App\Models\Student;
use Carbon\Carbon;
$factory->define(Student::class, function (Faker $faker) {
	$gender = $faker->randomElement(['Male', 'Female']);
	static $number = 1;
    return [
        'qbo_customer_id' => null,
        'application' => Carbon::today(),
        'lrn' => null,
        'department_id' => 1,
        'level_id' => 1,
        'track_id' => 1,
        'studentnumber' => 2000 . $number++,
        'new_or_old' => 'new',
        'photo' => '',
        'firstname' => $faker->firstName,
        'lastname' => $faker->lastName,
        'middlename' => str_random(1),
        'gender' => $gender,
        'birthdate' => $faker->date($format = 'Y-m-d', $max = 'now'),
        'citizenship' => null,
        'birthplace' => $faker->address,
        'residentialaddress' => $faker->address,
        'age' => 0,
        'street_number' => $faker->phoneNumber,
        'barangay' => str_random(10),
        'city_municipality' => str_random(10),
        'province' => str_random(10),
        'email' => $faker->safeEmail,
        'religion' => null,
        'legalguardian' => str_random(10),
        'legal_guardian_lastname' => $faker->lastName,
        'legal_guardian_firstname' => $faker->firstName,
        'legal_guardian_middlename' => str_random(1),
        'legal_guardian_citizenship' => str_random(10),
        'legal_guardian_occupation' => str_random(10),
        'legal_guardian_contact_number' => $faker->phoneNumber,
        'contactnumber' => $faker->phoneNumber,
        'previousschool' => $faker->address,
        'previousschooladdress' => $faker->address,
        'father' => str_random(10),
        'father_living_deceased' => 'living',
        'fatherfirstname' => $faker->firstName,
        'fatherlastname' => $faker->lastName,
        'fathermiddlename' => str_random(1),
        'fathercitizenship' => str_random(10),
        'fathervisastatus' => str_random(10),
        'father_occupation' => str_random(10),
        'fatheremployer' => str_random(10),
        'fatherofficenumber' => $faker->phoneNumber,
        'fatherMobileNumber' => $faker->phoneNumber,
        'mother' => str_random(10),
        'mother_living_deceased' => 'living',
        'motherlastname' => $faker->lastName,
        'motherfirstname' => $faker->firstName,
        'mothermiddlename' => str_random(1),
        'mothercitizenship' => str_random(10),
        'mothervisastatus' => str_random(10),
        'mother_occupation' => str_random(10),
        'motheremployer' => str_random(10),
        'motherOfficeNumber' => $faker->phoneNumber,
        'motherdegree' => str_random(10),
        'motherschool' => str_random(10),
        'mothernumber' => $faker->phoneNumber,
        'emergencycontactname' => str_random(10),
        'emergency_lastname' => $faker->lastName,
        'emergency_firstname' => $faker->firstName,
        'emergency_middlename' => str_random(1),
        'emergency_citizenship' => str_random(10),
        'emergencyofficephone' => str_random(10),
        'emergencymobilenumber' => $faker->phoneNumber,
        'emergencyaddress' => $faker->address ,
        'emergencyhomephone' => $faker->phoneNumber,
        'date' => Carbon::today(),
        'date2' => Carbon::today(),
    ];
});
