<style type="text/css">
	* {
		box-sizing: border-box;
		font-size: 12px;
	}

	body {
		margin: 0;
		font-family: Arial, Helvetica, sans-serif;

	}

	.text-center {
		text-align: center;
	}

	.text-right {
		text-align: right;
	}

	.d-block {
		display: block;
	}
	.m-0 {
		margin: 0;
		margin-bottom: 4px;
	}

	.wrapper {
		height: 100%; 
		min-width: 600px;
		width: auto; 
		background: #c3ced1; 
		padding: 60px;
		overflow-y: auto;
	}

	.second-wrapper {
		height: auto; 
		width: 80%; 
		background: #FFF; 
		margin: auto;
		position: relative;
	}
	
	.header {
		color: #FFF;
	}

	.body {
		background: #FFF;
	}

	.footer {
		/*position: absolute;*/
		background: #FFF;
		padding: 20px;
		width: 100%;
		}
</style>

<div class="wrapper">
	
	<div class="second-wrapper">
		
		<div class="header" style="padding: 20px; background: #0072bc;">
			<img src="{{ env('APP_URL') . '/' . config('settings.schoollogo') }}" alt="school logo" width="200" style="display: block; margin: auto;">
			<h1 class="text-center m-0" style="margin-top: 10px;">{{ config('settings.schoolname') }}</h1>
			<p class="text-center m-0" style="font-size: 12px;">{{ config('settings.schooladdress') }}</p>
		</div>
		<div class="body" style="padding: 20px;">
			<h3 class="text-center"><b>Welcome to {{ config('settings.schoolname') }} School!</b></h3>
			
			<p class="text-center" style="margin-top: 10px;">Your application has been sent! For verification purposes, kindly print the attached PDF File of your application form to be submitted with signatories signed together with your other requirements. </p>

			<p class="text-center">
				You have been successfully enlisted at <b style="text-transform: capitalize;">{{ config('settings.schoolname') }}</b> you can downlod your registration form <a href="{{ url('kiosk/download/enlist-form/' . $kiosk->kiosk_id) }}">here</a>.
			</p>
		</div>

		<div class="footer">
			<p class="text-center">This email is computer-generated by SchoolMATE Online. For more inquiries, email us at <a href="mailto:info@tigernetschool.com">info@tigernetschool.com</a></p>
			<img src="{{ asset('images/smo_logo.png') }}" alt="" width="80" style="display: block; margin: auto;">
		</div>

	</div>

</div>