<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ChartOfAccount extends Model
{
    public static function accountType ()
    {
        $data = [
		            'Bank' => [
		                'CashOnHand'		=> 'Use a Cash on hand account to track cash your company keeps for occasional expenses, also called petty cash. To track cash from sales that have not been deposited yet, use a pre-created account called Undeposited funds, instead.',
		                'Checking' 			=> 'Use Checking accounts to track all your checking activity, including debit card transactions. Each checking account your company has at a bank or other financial institution should have its own Checking type account in QuickBooks Online Plus.', 
		                'MoneyMarket' 		=> 'Use Money market to track amounts in money market accounts. For investments, see Other Current Assets, instead.',
		                'RentsHeldInTrust' 	=> 'Use Rents held in trust to track deposits and rent held on behalf of the property owners. Typically only property managers use this type of account.',
		                'Savings' 			=> 'Use Savings accounts to track your savings and CD activity. Each savings account your company has at a bank or other financial institution should have its own Savings type account. For investments, see Other Current Assets, instead.',
		                'TrustAccounts' 	=> 'Use Trust accounts for money held by you for the benefit of someone else. For example, trust accounts are often used by attorneys to keep track of expense money their customers have given them. Often, to keep the amount in a trust account from looking like it’s yours, the amount is offset in a "contra" liability account (a Current Liability).',
		            ],

		            'Other Current Asset' => [
		                'AllowanceForBadDebts' 				 => 'Use Allowance for bad debts to estimate the part of Accounts receivable you think you might not collect. Use this only if you are keeping your books on the accrual basis.',
		                'DevelopmentCosts' 					 => 'Use Development costs to track amounts you deposit or set aside to arrange for financing, such as an SBA loan, or for deposits in anticipation of the purchase of property or other assets. When the deposit is refunded, or the purchase takes place, remove the amount from this account.',
		                'EmployeeCashAdvances' 				 => 'Use Employee cash advances to track employee wages and salary you issue to an employee early, or other non-salary money given to employees. If you make a loan to an employee, use the Other current asset account type called Loans to others, instead.',
		                'OtherCurrentAssets' 				 => 'Use Other current assets for current assets not covered by the other types. Current assets are likely to be converted to cash or used up in a year.',
		                'Inventory' 						 => 'Use Inventory to track the cost of goods your business purchases for resale. When the goods are sold, assign the sale to a Cost of goods sold account.',
		                'Investment_MortgageRealEstateLoans' => 'Use Investments - Mortgage/real estate loans to show the balances of any mortgage or real estate loans your business has made or purchased.',
		                'Investment_Other' 					 => 'Use Investments - Other to track the value of investments not covered by other investment account types. Examples include publicly-traded stocks, coins, or gold.',
		                'Investment_TaxExemptSecurities' 	 => 'Use Investments - Tax-exempt securities for investments in state and local bonds, or mutual funds that invest in state and local bonds.',
		                'Investment_USGovernmentObligations' => 'Use Investments - U.S. government obligations for bonds issued by the U.S. government.',
		                'LoansToOfficers' 					 => 'If you operate your business as a Corporation or S Corporation, use Loans to officers to track money loaned to officers of your business.',
		                'LoansToOthers' 					 => 'Use Loans to others to track money your business loans to other people or businesses. This type of account is also referred to as Notes Receivable. For early salary payments to employees, use Employee cash advances, instead.',
		                'LoansToStockholders' 				 => 'If you operate your business as a Corporation or S Corporation, use Loans to stockholders to track money your business loans to its stockholders.',
		                'PrepaidExpenses' 					 => 'Use Prepaid expenses to track payments for expenses that you won’t recognize until your next accounting period. When you recognize the expense, make a journal entry to transfer money from this account to the expense account.',
		                'Retainage' 					 	 => 'Use Retainage if your customers regularly hold back a portion of a contract amount until you have completed a project. This type of account is often used in the construction industry, and only if you record income on an accrual basis.',
		                'UndepositedFunds' 					 => 'Use Undeposited funds for cash or checks from sales that haven’t been deposited yet. For petty cash, use Cash on hand, instead.',
		            ],
		            'Fixed Asset' => [
		            	'AccumulatedAmorization' 		=> 'Use Accumulated amortization to track how much you amortize intangible assets.',
		                'AccumulatedDepletion'			=> 'Use Accumulated depletion to track how much you deplete a natural resource.',
		                'AccumulatedDepreciation' 		=> 'Use Accumulated depreciation to track how much you depreciate a fixed asset (a physical asset you do not expect to convert to cash during one year of normal operations).',
		                'DepletableAssets' 				=> 'Use Depletable assets to track natural resources, such as timberlands, oil wells, and mineral deposits.',
		                'FixedAssetComputers' 			=> '',
		                'FixedAssetCopiers' 			=> '',
		                'FixedAssetFurniture' 			=> '',
		                'FixedAssetPhone' 				=> '',
		                'FixedAssetPhotoVideo' 			=> '',
		                'FixedAssetSoftware' 			=> '',
		                'FixedAssetOtherToolsEquipment' => '',
		                'FurnitureAndFixtures' 			=> 'Use Furniture & fixtures to track any furniture and fixtures your business owns and uses, like a dental chair or sales booth.',
		                'Land' 							=> 'Use Land for land or property you don’t depreciate. If land and building were acquired together, split the cost between the two in a logical way. One common method is to use the land-to-building ratio on the property tax statement. For land you use as a natural resource, use a Depletable assets account, instead.',
		                'LeaseholdImprovements' 		=> 'Use Leasehold improvements to track improvements to a leased asset that increases the asset’s value. For example, if you carpet a leased office space and are not reimbursed, that’s a leasehold improvement.',
		                'OtherFixedAssets' 				=> 'Use Other fixed asset for fixed assets that are not covered by other asset types. Fixed assets are physical property that you use in your business and that you do not expect to convert to cash or be used up during one year of normal operations.',
		                'IntangibleAssets' 				=> 'Use Intangible assets to track intangible assets that you plan to amortize. Examples include franchises, customer lists, copyrights, and patents.',
		                'MachineryAndEquipment' 		=> 'Use Machinery & equipment to track computer hardware, as well as any other non-furniture fixtures or devices owned and used for your business. This includes equipment that you ride, like tractors and lawn mowers. Cars and trucks, however, should be tracked with Vehicle accounts, instead.',
		                'Vehicles' 						=> 'Use Vehicles to track the value of vehicles your business owns and uses for business. This includes off-road vehicles, air planes, helicopters, and boats. If you use a vehicle for both business and personal use, consult your accountant or the IRS to see how you should track its value.',
		            ],
		            'Other Asset' => [
		                'LeaseBuyout'							=> 'Use Lease buyout to track lease payments to be applied toward the purchase of a leased asset. You don’t track the leased asset itself until you purchase it.',
		                'OtherLongTermAssets'					=> 'Use Other long-term assets to track assets not covered by other types. Long-term assets are expected to provide value for more than one year',
		                'SecurityDeposits'						=> 'Use Security deposits to track funds you’ve paid to cover any potential costs incurred by damage, loss, or theft. The funds should be returned to you at the end of the contract. If you collect deposits, use an Other current liabilities account type (an Other current liability account).',
		                'AccumulatedAmortizationOfOtherAssets'  => 'Use Accumulated amortization of other assets to track how much you’ve amortized asset whose type is Other Asset.',
		                'Goodwill'							    => 'Use Goodwill only if you have acquired another company. It represents the intangible assets of the acquired company which gave it an advantage, such as favorable government relations, business name, outstanding credit ratings, location, superior management, customer lists, product quality, or good labor relations.',
		                'Licenses'							    => 'Use Licenses to track non-professional licenses for permission to engage in an activity, like selling alcohol or radio broadcasting. For fees associated with professional licenses granted to individuals, use a Legal & professional fees expense account, instead.',
		                'OrganizationalCosts'				    => 'Use Organizational costs to track costs incurred when forming a partnership or corporation. The costs include the legal and accounting costs necessary to organize the company, facilitate the filings of the legal documents, and other paperwork.',
		            ],
		            'Equity' =>  [
		                'OpeningBalanceEquity' 		=> 'QuickBooks Online Plus creates this account the first time you enter an opening balance for a balance sheet account. As you enter opening balances, QuickBooks Online Plus records the amounts in Opening balance equity. This ensures that you have a correct balance sheet for your company, even before you’ve finished entering all your company’s assets and liabilities.', 
		                'PartnersEquity' 			=> 'Partnerships use Partner’s equity to show the income remaining in the partnership for each partner as of the end of the prior year.',
		                'RetainedEarnings' 			=> 'QuickBooks Online Plus adds this account when you create your company. Retained earnings tracks net income from previous fiscal years. QuickBooks Online Plus automatically transfers your profit (or loss) to Retained earnings at the end of each fiscal year.',
		                'AccumulatedAdjustment' 	=> 'S corporations use this account to track adjustments to owner’s equity that are not attributable to net income.',
		                'OwnersEquity' 				=> 'S corporations use Owner’s equity to show the cumulative net income or loss of their business as of the beginning of the fiscal year.',
		                'PaidInCapitalOrSurplus' 	=> 'Corporations use Paid-in capital to track amounts received from shareholders in exchange for stock that are over and above the stock’s stated (or par) value.',
		                'PartnerContributions' 		=> 'Partnerships use Partner contributions to track amounts partners contribute to the partnership during the year.',
		                'PartnerDistributions' 		=> 'Partnerships use Partner distributions to track amounts distributed by the partnership to its partners during the year. Don’t use this for regular payments to partners for interest or service. For regular payments, use a Guaranteed payments account (a Expense account in Payroll expenses), instead.',
		                'PreferredStock' 			=> 'Corporations use this account to track shares of its preferred stock in the hands of shareholders. The amount in this account should be the stated (or par) value of the stock.',
		                'CommonStock' 				=> 'Corporations use Common stock to track shares of its common stock in the hands of shareholders. The amount in this account should be the stated (or par) value of the stock.',
		                'TreasuryStock' 			=> 'Corporations use Treasury stock to track amounts paid by the corporation to buy its own stock back from shareholders.',
		            ],
		            'Expenses' => [
		                'AdvertisingPromotional' 				=> 'Use Advertising/promotional to track money spent promoting your company. You may want different accounts of this type to track different promotional efforts (Yellow Pages, newspaper, radio, flyers, events, and so on). If the promotion effort is a meal, use Promotional meals instead.',
		                'BadDebts' 								=> 'Use Bad debt to track debt you have written off.',
		                'BankCharges' 							=> 'Use Bank charges for any fees you pay to financial institutions.',
		                'CharitableContributions' 				=> 'Use Charitable contributions to track gifts to charity.',
		                'Entertainment' 						=> 'Use Entertainment to track events to entertain employees. If the event is a meal, use Entertainment meals, instead.',
		                'EntertainmentMeals' 					=> 'Use Entertainment meals to track how much you spend on dining with your employees to promote morale. If you dine with a customer to promote your business, use a Promotional meals account, instead.Be sure to include who you ate with and the purpose of the meal when you enter the transaction.',
		                'EquipmentRental' 						=> 'Use Equipment rental to track the cost of renting equipment to produce products or services. This account is also available as a Cost of Goods (COGS) account. If you purchase equipment, use a Fixed Asset account type called Machinery and equipment.',
		                'FinanceCosts' 							=> '',
		                'Insurance' 							=> 'Use Insurance to track insurance payments. You may want different accounts of this type for different types of insurance (auto, general liability, and so on).',
		                'InterestPaid' 							=> 'Use Interest paid for all types of interest you pay, including mortgage interest, finance charges on credit cards, or interest on loans.',
		                'LegalProfessionalFees' 				=> 'Use Legal & professional fees to track money to pay to professionals to help you run your business. You may want different accounts of this type for payments to your accountant, lawyer, or other consultants.',
		                'OfficeGeneralAdministrativeExpenses' 	=> 'Use Office/general administrative expenses to track all types of general or office-related expenses.',
		                'OtherBusinessExpenses' 				=> '',
		                'OtherMiscellaneousServiceCost' 		=> 'Use Other miscellaneous service cost to track costs related to providing services that don’t fall into another Expense type. This account is also available as a Cost of Goods Sold (COGS) account.',
		                'PromotionalMeals' 						=> 'Use Promotional meals to track how much you spend dining with a customer to promote your business. Be sure to include who you ate with and the purpose of the meal when you enter the transaction.',
		                'RentOrLeaseOfBuildings' 				=> 'Use Rent or lease of buildings to track rent payments you make.',
		                'RepairMaintenance' 					=> 'Use Repair & maintenance to track any repairs and periodic maintenance fees. You may want different accounts of this type to track different types repair & maintenance expenses (auto, equipment, landscape, and so on).',
		                'ShippingFreightDelivery' 				=> 'Use Shipping, freight & delivery to track the cost of shipping products to customers or distributors. You might use this type of account for incidental shipping expenses, and the Cost of Goods Sold type of Shipping, freight & delivery account for direct costs. This account is also available as a Cost of Goods Sold account.',
		                'SuppliesMaterials' 					=> 'Use Supplies & materials to track the cost of raw goods and parts used or consumed when producing a product or providing a service. This account is also available as a Cost of Goods Sold (COGS) account.',
		                'Travel' 								=> 'Use Travel to track travel costs. For food you eat while traveling, use Travel meals, instead.',
		                'TravelMeals' 							=> 'Use Travel meals to track how much you spend on food while traveling. If you dine with a customer to promote your business, use a Promotional meals account, instead. If you dine with your employees to promote morale, use Entertainment meals, instead.',
		                'Auto' 									=> 'Use Auto to track costs associated with vehicles. You may want different accounts of this type to track gasoline, repairs, and maintenance. If your business owns a car or truck, you may want to track its value as a Fixed Asset, in addition to tracking its expenses.',
		                'CostOfLabor' 							=> 'Use Cost of labor to track the cost of paying employees to produce products or supply services. It includes all employment costs, including food and transportation, if applicable. This account is also available as a Cost of Goods Sold (COGS) account.',
		                'DuesSubscriptions' 					=> 'Use Dues & subscriptions to track dues & subscriptions related to running your business. You may want different accounts of this type for professional dues, fees for licenses that can’t be transferred, magazines, newspapers, industry publications, or service subscriptions.',
		                'PayrollExpenses' 						=> 'Use Payroll expenses to track payroll expenses. You may want different accounts of this type for things like: Compensation of officers, Guaranteed payments, Workers compensation, Salaries and wages, Payroll taxes',
		                'TaxesPaid' 							=> 'Use Taxes paid to track taxes you pay. You may want different accounts of this type for payments to different tax agencies (sales tax, state tax, federal tax).',
		                'UnappliedCashBillPaymentExpense' 		=> 'Unapplied Cash Bill Payment Expense reports the Cash Basis expense from vendor payment checks you’ve sent but not yet applied to vendor bills. In general, you would never use this directly on a purchase or sale transaction. See IRS Publication 538.',
		                'Utilities' 							=> 'Use Utilities to track utility payments. You may want different accounts of this type to track different types of utility payments (gas and electric, telephone, water, and so on).',
		            ],
		            'Other Expense' => [
		                'Depreciation' 				=> 'Use Depreciation to track how much you depreciate fixed assets. You may want a depreciation account for each fixed asset you have.',
		                'ExchangeGainOrLoss' 		=> 'Use Exchange Gain or Loss to track gains or losses that occur as a result of exchange rate fluctuations.',
		                'OtherMiscellaneousExpense' => 'Use Other miscellaneous expense to track unusual or infrequent expenses that don’t fall into another Other Expense type.If an expense is directly related to providing a service, use an Expense type (not an Other Expense type) account called Other miscellaneous service cost.',
		                'PenaltiesSettlements' 		=> 'Use Penalties & settlements to track money you pay for violating laws or regulations, settling lawsuits, or other penalties.',
		                'Amortization' 				=> 'Use Amortization to track amortization of intangible assets. Amortization is spreading the cost of an intangible asset over its useful life, like depreciation of fixed assets. You may want an amortization account for each intangible asset you have.',
		                'GasAndFuel' 				=> '',
		                'HomeOffice' 				=> '',
		                'HomeOwnerRentalInsurance' 	=> '',
		                'OtherHomeOfficeExpenses' 	=> '',
		                'MortgageInterest' 			=> '',
		                'RentAndLease' 				=> '',
		                'RepairsAndMaintenance' 	=> '',
		                'ParkingAndTolls' 			=> '',
		                'Vehicle' 					=> '',
		                'VehicleInsurance' 			=> '',
		                'VehicleLease' 				=> '',
		                'VehicleLoanInterest' 		=> '',
		                'VehicleLoan' 				=> '',
		                'VehicleRegistration' 		=> '',
		                'VehicleRepairs' 			=> '',
		                'OtherVehicleExpenses' 		=> '',
		                'Utilities' 				=> '',
		                'WashAndRoadServices' 		=> '', 
		            ],
		            'Cost of Goods Sold' => [
		                'EquipmentRentalCos' 			=> 'Use Equipment rental - COS to track the cost of renting equipment to produce products or services. If you purchase equipment, use a Fixed Asset account type called Machinery and equipment.',
		                'OtherCostsOfServiceCos' 		=> 'Use Other costs of service - COS to track costs related to services you provide that don’t fall into another Cost of Goods Sold type.',
		                'ShippingFreightDeliveryCos' 	=> 'Use Shipping, freight & delivery - COGS to track the cost of shipping products to customers or distributors.',
		                'SuppliesMaterialsCogs' 		=> 'Use Supplies & materials - COGS to track the cost of raw goods and parts used or consumed when producing a product or providing a service.',
		                'CostOfLaborCos' 				=> 'Use Cost of labor - COS to track the cost of paying employees to produce products or supply services. It includes all employment costs, including food and transportation, if applicable.',
		               
		            ],
		            'Accounts Payable' => [
		                'Accounts Payable' => 'Accounts payable (also called A/P) tracks amounts you owe to your vendors and suppliers. QuickBooks Online Plus automatically creates one Accounts Payable account for you. Most businesses need only one.',
		            ],
		            'Credit Card' => [
		                'Credit Card' => 'Credit card accounts track the balance due on your business credit cards. Create one Credit card account for each credit card account your business uses.'
		            ],
		            'Long Term Liability' => [
		                'NotesPayable' 				=> 'Use Notes payable to track the amounts your business owes in long-term (over twelve months) loans. For shorter loans, use the Other current liability account type called Loan payable, instead.',
		                'OtherLongTermLiabilities' 	=> 'Use Other long term liabilities to track liabilities due in more than twelve months that don’t fit the other Long-term liability account types.',
		                'ShareholderNotesPayable' 	=> 'Use Shareholder notes payable to track long-term loan balances your business owes its shareholders.',
		            ],
		            'Other Current Liability' => [
		                'LineOfCredit' 					=> 'Use Line of credit to track the balance due on any lines of credit your business has. Each line of credit your business has should have its own Line of credit account.',
		                'LoanPayable' 					=> 'Use Loan payable to track loans your business owes which are payable within the next twelve months. For longer-term loans, use the Long-term liability called Notes payable, instead.',
		                'OtherCurrentLiabilities' 		=> 'Use Other current liabilities to track liabilities due within the next twelve months that do not fit the Other current liability account types.',
		                'PayrollClearing' 				=> 'Use Payroll clearing to keep track of any non-tax amounts that you have deducted from employee paychecks or that you owe as a result of doing payroll. When you forward money to the appropriate vendors, deduct the amount from the balance of this account. Do not use this account for tax amounts you have withheld or owe from paying employee wages. For those amounts, use the Payroll tax payable account instead.',
		                'PayrollTaxPayable' 			=> 'Use Payroll tax payable to keep track of tax amounts that you owe to Federal, State, and Local government agencies as a result of paying wages and taxes you have withheld from employee paychecks. When you forward the money to the government agency, deduct the amount from the balance of this account.',
		                'PrepaidExpensesPayable'		=> 'Use Prepaid expenses payable to track items such as property taxes that are due, but not yet deductible as an expense because the period they cover has not yet passed.',
		                'RentsInTrustLiability' 		=> 'Use Rents in trust - liability to offset the Rents in trust amount in assets. Amounts in these accounts are held by your business on behalf of others. They do not belong to your business, so should not appear to be yours on your balance sheet. This "contra" account takes care of that, as long as the two balances match.',
		                'TrustAccountsLiabilities' 		=> 'Use Trust accounts - liabilities to offset Trust accounts in assets. Amounts in these accounts are held by your business on behalf of others. They do not belong to your business, so should not appear to be yours on your balance sheet. This "contra" account takes care of that, as long as the two balances match.',
		                'FederalIncomeTaxPayable' 		=> 'Use Federal Income Tax Payable if your business is a corporation, S corporation, or limited partnership keeping records on the accrual basis. This account tracks income tax liabilities in the year the income is earned.',
		                'InsurancePayable' 				=> 'Use Insurance payable to keep track of insurance amounts due. This account is most useful for businesses with monthly recurring insurance expenses such as Workers’ Compensation.',
		                'SalesTaxPayable'  				=> 'Use Sales tax payable to track sales tax you have collected, but not yet remitted to the IRS.',
		                'StateLocalIncomeTaxPayable' 	=> 'Use State/local income tax payable if your business is a corporation, S corporation, or limited partnership keeping records on the accrual basis. This account tracks income tax liabilities in the year the income is earned.', 
		                'UndistributedTips' 			=> '',
		            ],
		            'Income' => [
		                'NonProfitIncome' 				=> 'Use Non-profit income to track money coming in if you are a non-profit organization.',
		                'OtherPrimaryIncome' 			=> 'Use Other primary income to track income from normal business operations that doesn’t fall into another Income type.',
		                'SalesOfProductIncome' 			=> 'Use Sales of product income to track income from selling products. This can include all kinds of products, like crops and livestock, rental fees, performances, and food served.',
		                'ServiceFeeIncome' 				=> 'Use Service/fee income to track income from services you perform or ordinary usage fees you charge. For fees customers pay you for late payments or other uncommon situations, use an Other Income account type called Other miscellaneous income, instead.',
		                'DiscountsRefundsGiven' 		=> 'Use Discounts/refunds given to track discounts you give to customers. This account typically has a negative balance so it offsets other income. For discounts from vendors, use an expense account, instead.',
		                'UnappliedCashPaymentIncome' 	=> 'Unapplied Cash Payment Income reports the Cash Basis income from customers payments you’ve received but not applied to invoices or charges. In general, you would never use this directly on a purchase or sale transaction. The IRS calls this "Constructive Receipt Income." See Publication 538.',
		            ],
		            'Other Income' => [
		                'DividendIncome' 			=> 'Use Dividend income to track taxable dividends from investments.',
		                'InterestEarned' 			=> 'Use Interest earned to track interest from bank or savings accounts, investments, or interest payments to you on loans your business made.',
		                'OtherInvestmentIncome' 	=> 'Use Other investment income to track other types of investment income that isn’t from dividends or interest.',
		                'OtherMiscellaneousIncome' 	=> 'Use Other miscellaneous income to track income that isn’t from normal business operations, and doesn’t fall into another Other Income type.',
		                'TaxExemptInterest' 		=> 'Use Tax-exempt interest to record interest that isn’t taxable, such as interest on money in tax-exempt retirement accounts, or interest from tax-exempt bonds.', 
		            ],               
            
        ];

        return $data;
    }
}
